# Generated by Django 5.1.7 on 2025-03-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_retest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='needs_retest',
            field=models.BooleanField(default=False),
        ),
    ]
